### ISSUE TITLE
RuntimeError: The size of tensor a (13) must match the size of tensor b (845) at non-singleton dimension 3

### ISSUE THREAD

**Issue by ShawnL1u** [marvis/pytorch-yolo2#106]
Hello,
I trained yolov2 on my own dataset and get a runtime error. The traceback is listed below.
```
Traceback (most recent call last):
  File "train.py", line 265, in <module>
    train(epoch)
  File "train.py", line 168, in train
    loss = region_loss(output, target)
  File "C:\Users\Shawn\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\2018Spring\Thesis\pytorch-yolo2-master\pytorch-yolo2-master\region_loss.py", line 142, in forward
    pred_boxes[0] = x.data + grid_x
RuntimeError: The size of tensor a (13) must match the size of tensor b (845) at non-singleton dimension 3
```

Can anyone help figure out what is going on? I am using cuda 9.1 on windows 10 with GTX 1070 GPU

**Comment by bilipa** [comment]
Before load weight to convolutional layer, reshape the weight shape first

**Comment by MatthewLQM** [comment]
I have the same issue when I'm trying to train my own dataset.
It seems to be an error because of the pytorch version.
I have pytorch version 0.4.0.

**Comment by doronAtuar** [comment]
Which pytorch version doesn't show this error?

**Comment by pulkit15158** [comment]
It works on pytorch version 0.2

**Comment by elixir-1** [comment]
Is there a solution to this? I got the same error for pytorch 0.4.0.

**Comment by lesreaper** [comment]
Running into the same issues as well, fresh install for Ubuntu.

**Comment by praveenkumarchandaliya** [comment]
I have test this type of problem on torch version  0.4,0.3.1,0.2  but till not get solved this problem.

 am also face same problem in ConvoutionLSTM

('encoder input size', (20L, 3L, 128L, 128L))
('x = ', 20)
('x.size(0) = ', (20L, 64L, 64L, 64L))
--------------------1
--------------------7
('encoder input size', (32L, 3L, 128L, 128L))
('x = ', 32)
('x.size(0) = ', (32L, 64L, 64L, 64L))
Traceback (most recent call last):
File "main.py", line 204, in 
fixed_z = netE(fixed_img_v, encoder_h_1, encoder_h_2, encoder_h_3)
File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in call
result = self.forward(*input, **kwargs)
File "/home/mnit/Desktop/RNN_CAAE_Pytorch_10Label/models.py", line 62, in forward
hidden1 = self.rnn1(x, hidden1)
File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in call
result = self.forward(*input, **kwargs)
File "/home/mnit/Desktop/RNN_CAAE_Pytorch_10Label/modules/conv_rnn.py", line 72, in forward
gates = self.conv_ih(input) + self.conv_hh(hx)
RuntimeError: The size of tensor a (32) must match the size of tensor b (20) at non-singleton dimension 0

**Comment by bilipa** [comment]
I'm sorry about my early answer.
This problem may cause by the .view() method parameters or shape mismatch problem.
In the region_loss.py. line 14 conf_mask has 2 dim, but in line 87 it seem has 4 dim. So you can add some code like conf_mask.view(nB, nA, nH, nW) before line 87.
Same, in line 135-141, you can change the nB*nA*nH*nW to nB, nA, nH, nW to match the shape. 
I think this can slove this problem.
By the way, I have not use the train code to check whether it is right, but i think you can try it :)

**Comment by sheepdnb** [comment]
Here is my code after applying fixes for this issue. Hope it helps.

`pred_boxes = torch.cuda.FloatTensor(4, nB*nA*nH*nW)`
`        grid_x = torch.linspace(0, nW-1, nW).repeat(nH,1).repeat(nB*nA, 1, 1).view(nB*nA*nH*nW).cuda()`
`        grid_y = torch.linspace(0, nH-1, nH).repeat(nW,1).t().repeat(nB*nA, 1, 1).view(nB*nA*nH*nW).cuda()`
`        anchor_w = torch.Tensor(self.anchors)`
`        anchor_w = anchor_w.view(nA, int(self.anchor_step))`
`        anchor_w = anchor_w.index_select(1, torch.LongTensor([0])).cuda()`
`        anchor_h = torch.Tensor(self.anchors).view(nA, int(self.anchor_step)).index_select(1, torch.LongTensor([1])).cuda()`
`        anchor_w = anchor_w.repeat(nB, 1).repeat(1, 1, nH*nW).view(nB*nA*nH*nW)`
`        anchor_h = anchor_h.repeat(nB, 1).repeat(1, 1, nH*nW).view(nB*nA*nH*nW)`
`#        pred_boxes[0] = x.data + grid_x`
`#        pred_boxes[1] = y.data + grid_y`
`#        pred_boxes[2] = torch.exp(w.data) * anchor_w`
`#        pred_boxes[3] = torch.exp(h.data) * anchor_h`
`        pred_boxes[0] = torch.reshape(x.data, (1,nB*nA*nH*nW)) + grid_x`
`        pred_boxes[1] = torch.reshape(y.data, (1,nB*nA*nH*nW)) + grid_yv
`        pred_boxes[2] = torch.reshape(torch.exp(w.data), (1,nB*nA*nH*nW)) * anchor_w`
`        pred_boxes[3] = torch.reshape(torch.exp(h.data), (1,nB*nA*nH*nW)) * anchor_h`

**Comment by PanTongLin** [comment]
> Here is my code after applying fixes for this issue. Hope it helps.
> 
> `pred_boxes = torch.cuda.FloatTensor(4, nB*nA*nH*nW)`
> ` grid_x = torch.linspace(0, nW-1, nW).repeat(nH,1).repeat(nB*nA, 1, 1).view(nB*nA*nH*nW).cuda()`
> ` grid_y = torch.linspace(0, nH-1, nH).repeat(nW,1).t().repeat(nB*nA, 1, 1).view(nB*nA*nH*nW).cuda()`
> ` anchor_w = torch.Tensor(self.anchors)`
> ` anchor_w = anchor_w.view(nA, int(self.anchor_step))`
> ` anchor_w = anchor_w.index_select(1, torch.LongTensor([0])).cuda()`
> ` anchor_h = torch.Tensor(self.anchors).view(nA, int(self.anchor_step)).index_select(1, torch.LongTensor([1])).cuda()`
> ` anchor_w = anchor_w.repeat(nB, 1).repeat(1, 1, nH*nW).view(nB*nA*nH*nW)`
> ` anchor_h = anchor_h.repeat(nB, 1).repeat(1, 1, nH*nW).view(nB*nA*nH*nW)`
> `# pred_boxes[0] = x.data + grid_x`
> `# pred_boxes[1] = y.data + grid_y`
> `# pred_boxes[2] = torch.exp(w.data) * anchor_w`
> `# pred_boxes[3] = torch.exp(h.data) * anchor_h`
> ` pred_boxes[0] = torch.reshape(x.data, (1,nB*nA*nH*nW)) + grid_x`
> ` pred_boxes[1] = torch.reshape(y.data, (1,nB*nA*nH*nW)) + grid_yv`
> ` pred_boxes[2] = torch.reshape(torch.exp(w.data), (1,nB*nA*nH*nW)) * anchor_w`
> ` pred_boxes[3] = torch.reshape(torch.exp(h.data), (1,nB*nA*nH*nW)) * anchor_h`

It works for me, thanks.
But there is a typo.
> ` pred_boxes[1] = torch.reshape(y.data, (1,nB*nA*nH*nW)) + grid_yv` <--- grid_y here

**Comment by phseidl** [comment]
a simple weights.view(-1,1) resolved the error for me
