### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by linus007** [marvis/pytorch-yolo2#14]
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 243, in <module>
    train(epoch)
  File "train.py", line 153, in train
    output = model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 58, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fourye/LearningLab/pytorch-yolo2/darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66

I use 1080Ti to train this, but failed and appear this error, who can help me?

**Comment by marvis** [comment]
pytorch dataloader have  a problem that when you stop the training process manually the memory is not released. If this is the only python process you run, you can find all the running python process and kill them, which will release the cuda memory.

**Comment by linus007** [comment]
I reboot, but still failed.

**Comment by marvis** [comment]
Can you give more details?

**Comment by linus007** [comment]
before i train this model, there still many gpu memory left.
![_015](https://user-images.githubusercontent.com/9405738/29158900-4531cfe6-7ddf-11e7-8fc3-28f9155d3c87.png)
after i train and type: python train.py cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23
then it would failed. 
there are more details you can have a see.
![image](https://user-images.githubusercontent.com/9405738/29159113-01f02cc2-7de0-11e7-912b-2a985c4e53f2.png)
![image](https://user-images.githubusercontent.com/9405738/29159126-0e597bee-7de0-11e7-974e-f13aebac5af4.png)

**Comment by marvis** [comment]
There is only one gpu on your machine. You need to set gpus=0
https://github.com/marvis/pytorch-yolo2/blob/master/cfg/voc.data#L5

**Comment by linus007** [comment]
before i train this model, i have changed it to 0. still failed. is it really ok in your machine?

**Comment by marvis** [comment]
@linus007  The code you run really doesn't support single gpu. Apologize! However, you can check the latest code now, which support single gpu training. BTW, you need to decrease the batch size if memory error again.

**Comment by linus007** [comment]
OK， thank u very much
