### ISSUE TITLE
CUDA out of memory 

### ISSUE THREAD

**Issue by ShadowGlory** [marvis/pytorch-yolo2#16]
The CUDA memory usage made me confused. I try to train the voc dataset with yolo-voc.cfg (batch=64
subdivisions=8), but I got error msg like below. It seems my gpu memory is not enough. Then I modified the yolo-voc.cfg with batch=32 subdivisions=4, the GPU usage is 7G.  But when the epoch reached 9000, the same memory error msg like blow is printed. I will be very appreciate for your help. 

BTW, if batch size is set to 64, how much GPU RAM I need for the training?

My PC and Software
GPU GTX 1070 8G RAM
CUDA 8.0
Ubuntu 16.04
Pytorch 0.2.0.post3 
Python 2.7

```
2017-09-01 17:33:45 epoch 0, processed 0 samples, lr 0.000100
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    train(epoch)
  File "train.py", line 161, in train
    output = model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 58, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shadowglory/pytorch-yolo2/darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66

```

```
Fri Sep  1 17:45:03 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0      On |                  N/A |
| 21%   55C    P2   186W / 180W |   7480MiB /  8112MiB |     68%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1006    G   /usr/lib/xorg/Xorg                              57MiB |
|    0      2174    G   /usr/lib/xorg/Xorg                             251MiB |
|    0      2811    G   compiz                                          73MiB |
|    0      3017    G   ...el-token=EC2FFFD10D633AB978546A4EC530D0C5    78MiB |
|    0      8018    C   python                                        6965MiB |
+-----------------------------------------------------------------------------+

```

**Comment by marvis** [comment]
Do you set the gpus params in https://github.com/marvis/pytorch-yolo2/blob/master/cfg/voc.data ? I tried for one gnu the batch size should be set at most 48 on my tian X gnu.  BTW, when you train yolo2, the images are randomly scaled from 320 ~ 608. 
https://github.com/marvis/pytorch-yolo2/blob/master/dataset.py#L38-L53
That's why you met the memory after batch 9000.

**Comment by ShadowGlory** [comment]
Thanks for your helpful answers.

**Comment by edgarmedina1801** [comment]
did you solve the problem? I realized used memory increases after some epochs. I'm in the limit memory using the default cfg. I would prefer to keep with the original memory usage.
