### ISSUE TITLE
how to convert the code could be run by pytorch 1.1

### ISSUE THREAD

**Issue by lunasdejavu** [marvis/pytorch-yolo2#161]
I encountered the error when I tried
`python detect.py cfg/yolo.cfg yolo.weights data/dog.jpg`
I modifed the code in cfg.py 
```
def load_conv(buf, start, conv_model):
    num_w = conv_model.weight.numel()
    num_b = conv_model.bias.numel()
    conv_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
    conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start + num_w]), (
    conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
    start = start + num_w
    # conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
    return start
```
```
def load_conv_bn(buf, start, conv_model, bn_model):
    num_w = conv_model.weight.numel()
    num_b = bn_model.bias.numel()
    bn_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));     start = start + num_b
    bn_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
    bn_model.running_mean.copy_(torch.from_numpy(buf[start:start+num_b]));  start = start + num_b
    bn_model.running_var.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
    conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start + num_w]), (
    conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
    start = start + num_w    
    # conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w 
    return start
```
by #84  to changed it to 0.4 version

but it showed the 

```
Traceback (most recent call last):
  File "detect.py", line 113, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 31, in detect
    boxes = do_detect(m, sized, 0.5, 0.4, use_cuda)
  File "C:\LPR\pytorch-yolo2\pytorch-yolo2\utils.py", line 372, in do_detect
    output = model(img)
  File "C:\Users\Willy_Sung\AppData\Local\Continuum\anaconda3\lib\site-packages\
torch\nn\modules\module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\LPR\pytorch-yolo2\pytorch-yolo2\darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "C:\Users\Willy_Sung\AppData\Local\Continuum\anaconda3\lib\site-packages\
torch\nn\modules\module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Willy_Sung\AppData\Local\Continuum\anaconda3\lib\site-packages\
torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\Willy_Sung\AppData\Local\Continuum\anaconda3\lib\site-packages\
torch\nn\modules\module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Willy_Sung\AppData\Local\Continuum\anaconda3\lib\site-packages\
torch\nn\modules\conv.py", line 340, in forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'padding' must be tuple of ints, but found element
 of type float at pos 1
```

does anyone know how to run it by 1.0?

**Comment by JJZHK** [comment]
in darknet.py, line 149, pad = int((kernel_size-1)/2 if is_pad else 0)
