### ISSUE TITLE
when i

### ISSUE THREAD

**Issue by Zouhanyu123** [marvis/pytorch-yolo2#162]
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    demo(cfgfile, weightfile)
  File "demo.py", line 34, in demo
    draw_img = plot_boxes_cv2(img, bboxes, None, class_names)
  File "E:\Python program\pytorch-yolo2-master\utils.py", line 212, in plot_boxes_cv2
    x1 = int(round((box[0] - box[2]//2.0) * width))
TypeError: type Tensor doesn't define __round__ method

what happened？

**Comment by Zouhanyu123** [comment]
I found a solution in 
utils.py 210

Delete ''round'' and Change to

for i in range(len(boxes)):
    box = boxes[i]
    x1 = int(((box[0] - box[2]/2.0) * width))
    y1 = int(((box[1] - box[3]/2.0) * height))
    x2 = int(((box[0] + box[2]/2.0) * width))
    y2 = int(((box[1] + box[3]/2.0) * height))

It's useful for me.
