### ISSUE TITLE
TypeError: view(): argument 'size' must be tuple of ints, but found element of type float at pos 3

### ISSUE THREAD

**Issue by 7heWorrior** [marvis/pytorch-yolo2#170]
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    demo(cfgfile, weightfile)
  File "demo.py", line 32, in demo
    bboxes = do_detect(m, sized, 0.5, 0.4, use_cuda)
  File "D:\EDI\YOLOv3_using_pytorch\pytorch-yolo2\utils.py", line 336, in do_detect
    output = model(img)
  File "C:\Users\Manas\.conda\envs\edi\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\EDI\YOLOv3_using_pytorch\pytorch-yolo2\darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "C:\Users\Manas\.conda\envs\edi\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\EDI\YOLOv3_using_pytorch\pytorch-yolo2\darknet.py", line 32, in forward
    x = x.view(B, C, H/hs, hs, W/ws, ws).transpose(3,4).contiguous()
TypeError: view(): argument 'size' must be tuple of ints, but found element of type float at pos 3

**Comment by xinxin12345** [comment]
@7heWorrior 请问这个问题您解决了吗

**Comment by christegho** [comment]
I got this error when I switched to Python3 from the code base developed to work with Python 2. 

You can fix this by changing pytorch-yolo2\darknet.py", line 32 to 
```
x.view(B, C, int(H/hs), hs, int(W/ws), ws)
```

This is because 7/2 in python2 returns an int but in python3m it returns a float. Another option is to use
```
x.view(B, C, H//hs, hs, W//ws, ws)
```
