### ISSUE TITLE
RuntimeError: Expected object of scalar type Float but got scalar type Double for argument #2 'other'

### ISSUE THREAD

**Issue by wudi00** [marvis/pytorch-yolo2#176]
When I train my own datasets, this error occurred:
`
Traceback (most recent call last):
  File "train.py", line 265, in <module>
    train(epoch)
  File "train.py", line 170, in train
    loss = region_loss(output, target)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/pytorch-yolo2-master/region_loss.py", line 158, in forward
    nH, nW, self.noobject_scale, self.object_scale, self.thresh, self.seen)
  File "/media/disk/wudi/pytorch-yolo2-master/region_loss.py", line 99, in build_targets
    iou = bbox_iou(gt_box, pred_box, x1y1x2y2=False) # best_iou
  File "/media/disk/wudi/pytorch-yolo2-master/utils.py", line 35, in bbox_iou
    mx = min(box1[0]-box1[2]/2.0, box2[0]-box2[2]/2.0)
RuntimeError: Expected object of scalar type Float but got scalar type Double for argument #2 'other'
`
Is the data type wrong during the calculation? Thanks!

**Comment by Aaronponceuv** [comment]
Hi
try modifying that line with int, since it's taking it as a float
