### ISSUE TITLE
RuntimeError: out of range ...  loss = loss + region_losses[i](outputs[i], target) when training voc

### ISSUE THREAD

**Issue by acrosson** [marvis/pytorch-yolo2#20]
I'm trying to train using the VOC PASCAL data set as described in readme. When I run `python train.py cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23` the models loads and then throws the following error:

```
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    train(epoch)
  File "train.py", line 172, in train
    loss = loss + region_losses[i](outputs[i], target)
  File "/home/stepai/anaconda3/envs/python2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stepai/alexander/pytorch-yolo2/region_loss.py", line 124, in forward
    nW = output.data.size(3)
RuntimeError: out of range at /py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/generic/THCTensor.c:23
```

The dimension of output is (125L, 13L, 13L).

**Comment by marvis** [comment]
Why there is no batch dimension? Do you set the batch size to 1?
