### ISSUE TITLE
Error when Training YOLO on VOC

### ISSUE THREAD

**Issue by neuhzhj2012** [marvis/pytorch-yolo2#31]
I failed in using train.py on VOC dataset. (CentOS Linux 7 (Core), python 2.7.5, torch.__version__: '0.1.12+4c35c63', )

-  UserWarning 
`
UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
`
- AttributeError
`
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    train(epoch)
  File "train.py", line 146, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/usr/lib64/python2.7/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/lib64/python2.7/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data1/cv_group/cv_user/pytorch-yolo2/dataset.py", line 62, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure)
  File "/data1/cv_group/cv_user/pytorch-yolo2/image.py", line 123, in load_data_detection
    img,flip,dx,dy,sx,sy = data_augmentation(img, shape, jitter, hue, saturation, exposure)
  File "/data1/cv_group/cv_user/pytorch-yolo2/image.py", line 49, in data_augmentation
    oh = img.height
  File "/usr/lib64/python2.7/PIL/Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: height
`

when i change  oh = height to oh = img.size[1], another AttributeError occur
`
  File "/usr/lib64/python2.7/PIL/Image.py", line 702, in convert
    im = im.convert(mode, dither)
ValueError: conversion from RGB to HSV not supported
`

**Comment by 4F2E4A2E** [comment]
does this happen with every image? Maybe you'll have to pre-process your images before training it. Most of the time, those error messages indicates a conversion problem. 
What does this command return for that image?
```
$ file <image>
```

**Comment by neuhzhj2012** [comment]
pre-process ? about what.  I just follow up the README.md.
when i run file <image>, i get
`
JPEG image data, JFIF standard 1.01
`

**Comment by andresmafladelgado** [comment]
Hello @neuhzhj2012 ,

I am having the same problem of width and height size. When I changed the line:

ow, oh = img.size

The "ValueError: conversion from RGB to HSV not supported" error appeared.

Could you solve it?

**Comment by andresmafladelgado** [comment]
After somewhat fixing the previous errors, now I am having another issue:

2017-10-23 13:31:00 training with 62.842919 samples/s
Traceback (most recent call last):
  File "train.py", line 264, in <module>
    test(epoch)
  File "train.py", line 230, in test
    all_boxes = get_region_boxes(output, conf_thresh, num_classes, anchors, num_anchors)
  File "/home/amafla/Documents/pytorch-yolo2/utils.py", line 132, in get_region_boxes
    xs = torch.sigmoid(output[0]) + grid_x
  File "/home/amafla/anaconda3/envs/py27/lib/python2.7/site-packages/torch/tensor.py", line 293, in __add__
    return self.add(other)
TypeError: add received an invalid combination of arguments - got (torch.FloatTensor), but expected one of:
 * (float value)

It apparently starts when the test(epoch) is called. Has anyone had this issue?

**Comment by neuhzhj2012** [comment]
@andresmafladelgado 
Upgrade python module.
`pip install -U pillow` 
Another problem appear: the program ran away. 
`505: nGT 1, recall 1, proposals 0, loss: x 0.617825, y 0.288245, w 3620.732910, h 1627.328247, conf 2.697436, cls 2.966156, total 5254.630859
506: nGT 6, recall 0, proposals 36, loss: x 0.322045, y 0.404236, w 387662.468750, h 112925.812500, conf 3.864422, cls 14.461620, total 500607.343750
507: nGT 2, recall 0, proposals 78, loss: x 5.864379, y 6.042421, w 206653936.000000, h 59746744.000000, conf 32.449043, cls 6.230494, total 266400736.000000
508: nGT 3, recall 0, proposals 113, loss: x 93.411926, y 95.272263, w 225058124556402688.000000, h 65111085732069376.000000, conf nan, cls 87.139267, total nan
509: nGT 1, recall 0, proposals 0, loss: x nan, y nan, w nan, h nan, conf nan, cls nan, total nan
510: nGT 1, recall 0, proposals 0, loss: x nan, y nan, w nan, h nan, conf nan, cls nan, total nan`

**Comment by MengXinChengXuYuan** [comment]
@neuhzhj2012 try to lower your lr like 0.0001
