### ISSUE TITLE
AttributeError: 'Darknet' object has no attribute 'module'

### ISSUE THREAD

**Issue by ronyuzhang** [marvis/pytorch-yolo2#35]
when i run training on my widerface data, i have a error as follows:
----
Traceback (most recent call last):
  File "train_face.py", line 194, in <module>
    train(epoch)
  File "train_face.py", line 115, in train
    cur_model = model.module
  File "/usr/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 262, in __getattr__
    type(self).__name__, name))
AttributeError: 'Darknet' object has no attribute 'module'

**Comment by pluto16** [comment]
Do you use multi gpus?  class DataParallel in pytorch has attribuite 'module'

**Comment by DreadPiratePsyopus** [comment]
@ronyuzhang , @pluto16 
Were you successful at multi-gpu training?
