### ISSUE TITLE
use faster branch, detect.py has error.

### ISSUE THREAD

**Issue by Jmx5200** [marvis/pytorch-yolo2#4]
after run `python detect.py cfg/yolo.cfg yolo.weights data/dog.jpg` , error occur. but the master branch is ok.
```
Traceback (most recent call last):
  File "detect.py", line 44, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 31, in detect
    boxes = do_detect(m, sized, 0.5, 0.4, use_cuda)
  File "/home/mx/pytorch-yolo2/utils.py", line 283, in do_detect
    output = model(img)
  File "/home/mx/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes exactly 3 arguments (2 given)
```

**Comment by marvis** [comment]
faster branch is just a experimental version
