### ISSUE TITLE
VOC training custom data problem

### ISSUE THREAD

**Issue by JunShao-Hub** [marvis/pytorch-yolo2#44]
Hello, I used VOC to train custom data in the following errors. How can I solve it?

Traceback (most recent call last):
  File "train.py", line 98, in <module>
    params_dict = dict(model.named_parameters())
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 237, in __getattr__
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

**Comment by wtnan2003** [comment]
Same question

Traceback (most recent call last):
  File "train.py", line 102, in <module>
    params_dict = dict(model.named_parameters())
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 237, in __getattr__
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

how can I solve it?
