### ISSUE TITLE
RuntimeError: argument 1 must be tuple of int, not tuple

### ISSUE THREAD

**Issue by sheacoding** [marvis/pytorch-yolo2#48]
When I run `optirun python detect.py cfg/yolo.cfg yolo.weights data/dog.jpg`
It runtime error:
`Loading weights from yolo.weights... Done!
Traceback (most recent call last):
  File "detect.py", line 113, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 31, in detect
    boxes = do_detect(m, sized, 0.5, 0.4, use_cuda)
  File "/home/shea/Pytorch/pytorch-yolo2/utils.py", line 336, in do_detect
    output = model(img)
  File "/home/shea/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shea/Pytorch/pytorch-yolo2/darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "/home/shea/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shea/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/home/shea/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shea/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/shea/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 39, in conv2d
    _pair(0), groups, torch.backends.cudnn.benchmark, torch.backends.cudnn.enabled)
RuntimeError: argument 1 must be tuple of int, not tuple`
OS:Linux  Python3.5.4   Pytorch  0.1.12_1

**Comment by AmIr-KinG** [comment]
check this
https://github.com/pytorch/pytorch/issues/2593#issuecomment-326522292

**Comment by edgarmedina1801** [comment]
Maybe this is due to you are using python3. I solved the problem with  // or   int(.)

**Comment by bharath5673** [comment]
In python2, 7 / 2 = 3, but in python3, 7 / 2 = 3.5, and 7 // 2 = 3.
I think you only need to change this line so that pad will be an int.[](url)
