### ISSUE TITLE
My result is only 57mAP, can anyone help me ?

### ISSUE THREAD

**Issue by wwxJream** [marvis/pytorch-yolo2#65]
I use `python train.py cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23` to train the yolo2.
After 200 epochs, I use `python valid.py cfg/voc.data cfg/yolo-voc.cfg ./backup/000200.weights` and `python scripts/voc_eval.py results/comp4_det_test_` to evaluate. But the score is only `Mean AP = 0.5783`. What's wrong?

**Comment by Bigwode** [comment]
hah, I got 63.83% AP after training on VOC2007 and VOC2012, a low precision........................

**Comment by Sunyouteng** [comment]
> 
> 
> I use `python train.py cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23` to train the yolo2.
> After 200 epochs, I use `python valid.py cfg/voc.data cfg/yolo-voc.cfg ./backup/000200.weights` and `python scripts/voc_eval.py results/comp4_det_test_` to evaluate. But the score is only `Mean AP = 0.5783`. What's wrong?

can i ask you about when i use ` python scripts/voc_eval.py results/comp4_det_test_ `to evaluate. an error happens

> Saving cached annotations to /home/yruijia/distiller/examples/pytorch-yolo2/train_voc/VOCdevkit/annotations_cache/annots.pkl
Traceback (most recent call last):
  File "/home/yruijia/distiller/examples/pytorch-yolo2/scripts/voc_eval.py", line 263, in <module>
    _do_python_eval(res_prefix, output_dir = 'output')
  File "/home/yruijia/distiller/examples/pytorch-yolo2/scripts/voc_eval.py", line 239, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/yruijia/distiller/examples/pytorch-yolo2/scripts/voc_eval.py", line 115, in voc_eval
    pickle.dump(recs, f)
TypeError: write() argument must be str, not bytes
 so can you help?

**Comment by Zhefei777** [comment]
Hello, when i use voc_eval.py , I got this error 
  File "scripts/voc_eval.py", line 209
    filename = <res_prefix + '{:s}.txt'>
             ^
SyntaxError: invalid syntax

Could anyone help me ?

**Comment by DeepPower** [comment]
@Sunyouteng It may caused by python version. After I used python2 and changed pickle to cPickle, this error disappear.

**Comment by Sunyouteng** [comment]
@DeepPower Thanks for your reply.
