### ISSUE TITLE
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

### ISSUE THREAD

**Issue by LShuohao** [marvis/pytorch-yolo2#84]
nvidia@tegra-ubuntu:~/pytorch-yolo2$ python detect.py cfg/yolo.cfg yolo.weights data/dog.jpg
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
    1 max          2 x 2 / 2   416 x 416 x  32   ->   208 x 208 x  32
    2 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64
    3 max          2 x 2 / 2   208 x 208 x  64   ->   104 x 104 x  64
    4 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    5 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64
    6 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    7 max          2 x 2 / 2   104 x 104 x 128   ->    52 x  52 x 128
    8 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
    9 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128
   10 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
   11 max          2 x 2 / 2    52 x  52 x 256   ->    26 x  26 x 256
   12 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   13 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   14 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   15 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   16 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   17 max          2 x 2 / 2    26 x  26 x 512   ->    13 x  13 x 512
   18 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   19 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   20 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   21 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   22 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 conv     64  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x  64
   27 reorg              / 2    26 x  26 x  64   ->    13 x  13 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    13 x  13 x1280   ->    13 x  13 x1024
   30 conv    425  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 425
   31 detection
Traceback (most recent call last):
  File "detect.py", line 113, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 12, in detect
    m.load_weights(weightfile)
  File "/home/nvidia/pytorch-yolo2/darknet.py", line 265, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "/home/nvidia/pytorch-yolo2/cfg.py", line 175, in load_conv_bn
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w 
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

**Comment by Prausome** [comment]
what is your pytorch version? 
I had same error with the last version of pytorch. 
I changed  this code.
conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w 
==> conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start+num_w],(conv_model.weight.shape[0],conv_model.weight.shape[1], conv_model.weight.shape[2])))); start=start + num_w
It worked for me.

**Comment by brchlluk** [comment]
Same error for me, torch version is 0.4

**Comment by LShuohao** [comment]
thank prausome. I have solved this problem.

**Comment by griz1112** [comment]
LShuohao how did you solve this I am having the same issue.

**Comment by eduardolcordeiro** [comment]
I am having the exact same problem.
@horvitzs Solutions did not work.

**Comment by eduardolcordeiro** [comment]
The actual solution is this: conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start+num_w]),(conv_model.weight.shape[0],conv_model.weight.shape[1], conv_model.weight.shape[2],conv_model.weight.shape[3]))); start=start + num_w

@griz1112

**Comment by griz1112** [comment]
Thanks I had tried that but failed to notice it needed to be changed in two places. Working great now.

**Comment by MaratZakirov** [comment]
Does not work for me

**Comment by horvathdeli** [comment]
These are the 2 changed functions, which definitely work for me! 
```
def load_conv(buf, start, conv_model):
    num_w = conv_model.weight.numel()
    num_b = conv_model.bias.numel()
    conv_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
    conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start + num_w]), (
    conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
    start = start + num_w
    #conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
    return start

def load_conv_bn(buf, start, conv_model, bn_model):
    num_w = conv_model.weight.numel()
    num_b = bn_model.bias.numel()
    bn_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));     start = start + num_b
    bn_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
    bn_model.running_mean.copy_(torch.from_numpy(buf[start:start+num_b]));  start = start + num_b
    bn_model.running_var.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
    conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start + num_w]), (
    conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
    start = start + num_w
    #conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
    return start
```

**Comment by praveenkumarchandaliya** [comment]
Any one help this problem i am using torch 0.3.1 version

('encoder input size', (20L, 3L, 128L, 128L))
('x = ', 20)
('x.size(0) = ', (20L, 64L, 64L, 64L))
--------------------1
--------------------7
('encoder input size', (32L, 3L, 128L, 128L))
('x = ', 32)
('x.size(0) = ', (32L, 64L, 64L, 64L))
Traceback (most recent call last):
File "main.py", line 204, in 
fixed_z = netE(fixed_img_v, encoder_h_1, encoder_h_2, encoder_h_3)
File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in call
result = self.forward(*input, **kwargs)
File "/home/mnit/Desktop/RNN_CAAE_Pytorch_10Label/models.py", line 62, in forward
hidden1 = self.rnn1(x, hidden1)
File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in call
result = self.forward(*input, **kwargs)
File "/home/mnit/Desktop/RNN_CAAE_Pytorch_10Label/modules/conv_rnn.py", line 72, in forward
gates = self.conv_ih(input) + self.conv_hh(hx)
**RuntimeError: The size of tensor a (32) must match the size of tensor b (20) at non-singleton dimension 0**

**Comment by shenglin1987** [comment]
I use pytorch0.4.0 and torchvision0.18.0. I face the same problem. After I update the torchvision to 0.2.1. The problem is solved.

**Comment by m3rcury6** [comment]
> The actual solution is changing conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
> to
> conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start+num_w]),(conv_model.weight.shape[0],conv_model.weight.shape[1], conv_model.weight.shape[2],conv_model.weight.shape[3]))); start=start + num_w
> 
> @griz1112

this seems to have fixed it for me as well, since the other suggestions didn't do the trick. thanks to everyone for the help

**Comment by lovelingclear** [comment]
I face the same question when I want to turn conv2D to conv3D on HSI

**Comment by Ashkan8** [comment]
> 
> 
> The actual solution is changing conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
> to
> conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start+num_w]),(conv_model.weight.shape[0],conv_model.weight.shape[1], conv_model.weight.shape[2],conv_model.weight.shape[3]))); start=start + num_w
> 
> @griz1112

Thanks. It works very well

**Comment by Ashkan8** [comment]
In below function (yolov2-->cfg.py), I have a error after solution changing 
------------------------------------------
(conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
to
conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start+num_w]),(conv_model.weight.shape[0],conv_model.weight.shape[1], conv_model.weight.shape[2],conv_model.weight.shape[3]))); start=start + num_w
--------------------------------------------------------------------------
def load_conv(buf, start, conv_model):
    num_w = conv_model.weight.numel()
    num_b = conv_model.bias.numel()
    conv_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
    
    return start
---------------------------------------------
RuntimeError: The expanded size of the tensor (1) must match the existing size (127701) at non-singleton dimension 3.  Target sizes: [425, 1024, 1, 1].  Tensor sizes: [127701]

help me, please

**Comment by I-Guitar** [comment]
> The actual solution is changing conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
> to
> conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start+num_w]),(conv_model.weight.shape[0],conv_model.weight.shape[1], conv_model.weight.shape[2],conv_model.weight.shape[3]))); start=start + num_w
> 
> @griz1112

Thanks, it works

**Comment by yiintong** [comment]
thanks ，although it works but it appears new problem .
pytorch 1.31
python 3.74

**Comment by I-Guitar** [comment]
> thanks ，although it works but it appears new problem .
> pytorch 1.31
> python 3.74

Found no NVIDIA driver on your system?

**Comment by yiintong** [comment]
> > thanks ，although it works but it appears new problem .
> > pytorch 1.31
> > python 3.74
> 
> Found no NVIDIA driver on your system?

it is” output with shape [255, 1024, 1, 1] doesn't match the broadcast shape [255, 1024, 1, 261120]”
and I solved it right now.
i am a green hand and i am learning it

**Comment by Noah-CV** [comment]
> These are the 2 changed functions, which definitely work for me!
> 
> ```
> def load_conv(buf, start, conv_model):
>     num_w = conv_model.weight.numel()
>     num_b = conv_model.bias.numel()
>     conv_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
>     conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start + num_w]), (
>     conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
>     start = start + num_w
>     #conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
>     return start
> 
> def load_conv_bn(buf, start, conv_model, bn_model):
>     num_w = conv_model.weight.numel()
>     num_b = bn_model.bias.numel()
>     bn_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));     start = start + num_b
>     bn_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
>     bn_model.running_mean.copy_(torch.from_numpy(buf[start:start+num_b]));  start = start + num_b
>     bn_model.running_var.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
>     conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start + num_w]), (
>     conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
>     start = start + num_w
>     #conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
>     return start
> ```

非常感谢 有用 我的环境torch==1.3.0 python==2.7

**Comment by SuperSivan** [comment]
> These are the 2 changed functions, which definitely work for me!
> 
> ```
> def load_conv(buf, start, conv_model):
>     num_w = conv_model.weight.numel()
>     num_b = conv_model.bias.numel()
>     conv_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
>     conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start + num_w]), (
>     conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
>     start = start + num_w
>     #conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
>     return start
> 
> def load_conv_bn(buf, start, conv_model, bn_model):
>     num_w = conv_model.weight.numel()
>     num_b = bn_model.bias.numel()
>     bn_model.bias.data.copy_(torch.from_numpy(buf[start:start+num_b]));     start = start + num_b
>     bn_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
>     bn_model.running_mean.copy_(torch.from_numpy(buf[start:start+num_b]));  start = start + num_b
>     bn_model.running_var.copy_(torch.from_numpy(buf[start:start+num_b]));   start = start + num_b
>     conv_model.weight.data.copy_(torch.reshape(torch.from_numpy(buf[start:start + num_w]), (
>     conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
>     start = start + num_w
>     #conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
>     return start
> ```

Thank you very much,it really works!

**Comment by anisaha1** [comment]
> > > thanks ，although it works but it appears new problem .
> > > pytorch 1.31
> > > python 3.74
> > 
> > 
> > Found no NVIDIA driver on your system?
> 
> it is” output with shape [255, 1024, 1, 1] doesn't match the broadcast shape [255, 1024, 1, 261120]”
> and I solved it right now.
> i am a green hand and i am learning it

@yiintong How did you solve this?
