### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0

### ISSUE THREAD

**Issue by wxjeacen** [marvis/pytorch-yolo2#89]
The training data is VOC 2007.
I have decreased the batch size as to 24 and learning rate as to 0.000375. 

I can get two backup weight files, but there is an exception as below.

Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train(epoch)
  File "train.py", line 150, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 267, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 135, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 112, in default_collate
    return torch.stack(batch, 0, out=out)
  File "/usr/local/lib/python2.7/dist-packages/torch/functional.py", line 66, in stack
    return torch.cat(inputs, dim, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 416 and 480 in dimension 2 at /pytorch/torch/lib/TH/generic/THTensorMath.c:2897

**Comment by wxjeacen** [comment]
Anyone can help me?

**Comment by supertonyliu** [comment]
I met the same problem

**Comment by wxjeacen** [comment]
@supertonyliu  Have you got a solution?

**Comment by anewlearner** [comment]
any updata?

**Comment by Bixbeat** [comment]
I stumbled upon this thread after running into a similar issue. The error message notifies you that you should have equal width and height dimensions, which in your case did not happen. ' Sizes of tensors must match except in dimension 0. Got 416 and 480 '.
Try putting a crop in your input data, e.g. transforms.RandomCrop(224) (or whichever size is required for YOLO V2. This fixed the dimensions mismatch for me.

**Comment by unnir** [comment]
the solution is to use the batch with a size 1. 

here is the explanation:
https://medium.com/@yvanscher/pytorch-tip-yielding-image-sizes-6a776eb4115b

**Comment by Silber8806** [comment]
Had the same issue and used BixBeat suggestion to get it to work.

**Comment by leadcain84** [comment]
I met same problem.
I thinks, when train, it is derived from different batch size between batch_size and train data loader.
if you set same batch size in train, no different size images are loaded to the loader.
for example) 
  if 256 batch size images are loaded to train loader,  you use 256 batch size images.
  So, there are no different size images are left.
 
I change some code in dataset.py, It work correctly
   def __getimte__(.....)
    ....
   if self.seen < 4000 * 64:  --> self.seen < 4000*batch_size

Thank you marvis, It is great code.

**Comment by santhoshnumberone** [comment]
Using @Bixbeat suggestion `RandomSize` i got this error

> Traceback (most recent call last):
>   File "demotest1.py", line 222, in <module>
>     model_ft = train_model(model_ft,criterion,optimizer_ft,exp_lr_scheduler,num_epochs=2)
>   File "demotest1.py", line 119, in train_model
>     for i, (inputs,labels) in enumerate(dataloaders[phase]):
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
>     return self._process_next_batch(batch)
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
>     raise batch.exc_type(batch.exc_msg)
> ValueError: Traceback (most recent call last):
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 103, in __getitem__
>     sample = self.transform(sample)
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
>     img = t(img)
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 421, in __call__
>     i, j, h, w = self.get_params(img, self.size)
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 399, in get_params
>     i = random.randint(0, h - th)
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/random.py", line 221, in randint
>     return self.randrange(a, b+1)
>   File "/home/ffffff/.virtualenvs/LearnPytorch/lib/python3.6/random.py", line 199, in randrange
>     raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
> ValueError: empty range for randrange() (0,-29, -29)

Using `RandomSizeCrop` solved my problem

**Comment by apacha** [comment]
As Bixbeat mentioned, it is not related to Yolo. In my case I was using `transforms.Resize(128)` instead of `transforms.Resize((128,128))` which caused the trouble.

**Comment by luzhilin19951120** [comment]
For some dataset, the image you load is not of the same format.

For instance, there can be GRB images and grey images.

So the following codes may help settling this bug __under certain case__
``` python
from PIL import Image
def _read_image(self, image_path):
    image = Image.open(image_path)
    if image.getbands()[0] == 'L':
        image = image.convert('RGB')
    return image
```

**Comment by amsun10** [comment]
@wxjeacen how old are you

**Comment by wxjeacen** [comment]
@amsun10 you mother fucker shut up

**Comment by kangkang59812** [comment]
@Bixbeat thanks! But if I dont want to crop my images, the only way is to set 'Batch_Size=1'??

**Comment by amsun10** [comment]
Who the motherfucker gaved us a thumbs down? @wxjeacen

**Comment by wxjeacen** [comment]
@amsun10 I do not know,  However, please mother fucker shut up, cause you know shit about this thread.

**Comment by fatemeakbari** [comment]
hello 
I had the same problem, I guess this code may help you
`    def __init__(self, imgs_path, csv_path=None, transform=None):
        
        self.imgs_path = imgs_path
        self.labels = pds.read_csv(csv_path)
        self.transform = transform
     
    def __len__(self):
        return len(self.labels)
    
    def __getitem__(self, index):
     
        img_name = self.labels.iloc[index,0]
        
        label = self.labels.iloc[index, 1:].values.astype('float')
        label = label[~np.isnan(label)].reshape(-1,4) 
        
        img_path = os.path.join(self.imgs_path,img_name)
        img = io.imread(img_path)
        img = resize(img, (300,300))
	img = torch.from_numpy(sample[0].transpose(2, 0, 1))
	
        
        #print(type(img),type(label))#torch.tensor, numpy array
        return img,label


dataset = Transform(imgs_path,csv_path)
data_loader = DataLoader(dataset,batch_size=4,shuffle=True,num_workers=0, collate_fn=detection_collate)
`
you can use "collate_fn" for this problem.
I summarized my code, this is not complete
you can see:  https://github.com/amdegroot/ssd.pytorch

**Comment by stonarda** [comment]
My problem was that using PIL to read in images sometimes created tensors of shape (1, 256, 256) rather than RGB (3, 256, 256). This is because some of my training set contained greyscale images. As a result I added a check for this, and if it was single channel I simply duplicated that channel 3 times to get 'RGB' of sorts.

**Comment by VDeamoV** [comment]
> For some dataset, the image you load is not of the same format.
> 
> For instance, there can be GRB images and grey images.
> 
> So the following codes may help settling this bug **under certain case**
> 
> ```python
> from PIL import Image
> def _read_image(self, image_path):
>     image = Image.open(image_path)
>     if image.getbands()[0] == 'L':
>         image = image.convert('RGB')
>     return image
> ```

Thanks a lot, it work for me

**Comment by LiangChengming** [comment]
Here is my solution:

- make sure your have **same shapes of images** (".convert('RGB')" will fix this)
- make sure your have **same shapes of labels** (fix it your self)

`@Bixbeat thanks! But if I dont want to crop my images, the only way is to set 'Batch_Size=1'??`

set Batch_Size=1 shadows the real error that you are combining different shape of data(tensors) as a batch(one big tensor)

**Comment by Datasciencehome** [comment]
> 
> 
> I stumbled upon this thread after running into a similar issue. Not directly related to YOLO V2, but it might be of help here. The error message notifies you that you should have equal width and height dimensions, which in your case did not happen. ' Sizes of tensors must match except in dimension 0. Got 416 and 480 '.
> Try putting a crop in your input transforms, e.g. transforms.RandomCrop(224) (or whichever size is required for YOLO V2). This fixed the dimensions mismatch in my case. Hopefully for yours too.

I found the problem was that I had to convert the images to RGB. Now the input dimensions match, there were broken images. Thank you @Bixbeat

**Comment by shihyung** [comment]
different size issue might be fixed by adding collate_fn=utils.collate_fn when calling DataLoader,
as least it works for me :p

**Comment by Spandyie** [comment]
@LiangChengming  I am getting the same issue, but here I am trying to convert ".dcm" to "RGB" using the following code 

     `img_array = pydicom.read_file(data_dir + name).pixel_array.astype(np.float32)
        # convert to PIL image before transforming it
        img = PIL.Image.fromarray(img_array)
        #if img.getbands()[0] == 'L':
        #    img = img.convert('RGB')
        #convert Grayscale to RGB
        img = img.convert("RGB")`

**Comment by imrekovacs** [comment]
I had the same issue: Using transforms.RandomRotation does alter the image-sizes. This can be solved by cropping (using RandomResizedCrop) the images after rotation:
```
train_data_transform = transforms.Compose([transforms.RandomRotation(20,resample=Image.BICUBIC,expand=True),
                                           transforms.RandomResizedCrop(FSIZE),
                                           transforms.RandomHorizontalFlip(),                                          
                                           transforms.ToTensor(),
                                           transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
```

**Comment by jiawenhao2015** [comment]
same error,finally i find that my label is wrong, the right form is [ 0,0,0,0] ,but there is a label is [0,0,0,0,0,0,0,0] ,the dim is wrong!!!!

**Comment by Ginbor** [comment]
in my case, the problem disappeared when I didn't use savemodel() function. I suppose that the problem appears after cur_model.save_weights(). also in my case i have train dataset that len(train_dataset)%batch_size = 0
