### ISSUE TITLE
truths_length returns None

### ISSUE THREAD

**Issue by wxjeacen** [marvis/pytorch-yolo2#99]
cls_confs = torch.nn.Softmax()(Variable(output[5:5+num_classes].transpose(0,1))).data
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    test(epoch)
  File "train.py", line 233, in test
    total = total + num_gts
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

num_gts is return from 'truths_length ' function.
```python
    def truths_length(truths):
        for i in range(50):
            if truths[i][1] == 0:
                return i
```
Here there is no 'else' branch and returned None

**Comment by wxjeacen** [comment]
And I was also confused about the hard code 50 ...

**Comment by wxjeacen** [comment]
@iceflame89  any suggestions?

**Comment by sheepdnb** [comment]
I'm guessing you're using a dataset where a labeled image has >50 labeled objects. I fixed this the following way:

In train.py I changed the range from 50 to 100 (just because my datasets never exceeded 75 objects / img):
`def test(epoch):
    def truths_length(truths):
        for i in range(100):
            if truths[i][1] == 0:
                return i`

In dataset.py I also replaced all hardcoded 50's with 100. 
`            label = torch.zeros(100*5)
            try:
                tmp = torch.from_numpy(read_truths_args(labpath, 8.0/img.width).astype('float32'))
            except Exception:
                tmp = torch.zeros(1,5)
            tmp = tmp.view(-1)
            tsz = tmp.numel()
            if tsz > 100*5:
                label = tmp[0:100*5]
            elif tsz > 0:
                label[0:tsz] = tmp`

The NoneType issue occurs because datasets.py preallocates labels as a 50x5 torch zeros tensor, and uses the first line of zeros as the indication that all the relevant objects in the label have been read. Hope that helps
